//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EonBarcodeEntities : DbContext
    {
        public EonBarcodeEntities()
            : base("name=EonBarcodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AdminUsers> tbl_AdminUsers { get; set; }
        public virtual DbSet<tbl_Barcodes> tbl_Barcodes { get; set; }
        public virtual DbSet<tbl_BarcodeUsers> tbl_BarcodeUsers { get; set; }
        public virtual DbSet<tbl_ClientUsers> tbl_ClientUsers { get; set; }
        public virtual DbSet<tbl_BarcodeSet> tbl_BarcodeSet { get; set; }
    }
}
