//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BarcodeTransactions
    {
        public long BarcodeTransactionId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> QRCodeId { get; set; }
        public Nullable<bool> IsDebit { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
