//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BarcodeUsers
    {
        public long BarcodeUserId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> BarcodeId { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public Nullable<bool> IsAmountSettled { get; set; }
        public Nullable<System.DateTime> SettledDate { get; set; }
        public Nullable<long> SettledBy { get; set; }
    }
}
