//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Setting
    {
        public long SettingId { get; set; }
        public string HomeRewardPointImage { get; set; }
    }
}
